[build]
builder = "DOCKERFILE"
dockerfilePath = "apps/server/Dockerfile"
watchPatterns = [
  "apps/server/**",
  "packages/**",
  "pnpm-lock.yaml"
]

[deploy]
startCommand = "pnpm -F @proj-airi/api-server start"
